/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TimeTrackingRouteImport } from './routes/time-tracking'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SubcontractorsRouteImport } from './routes/subcontractors'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesCatalogRouteImport } from './routes/services-catalog'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SalesCatalogRouteImport } from './routes/sales-catalog'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PreventiveMaintenanceRouteImport } from './routes/preventive-maintenance'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OnlineBookingRouteImport } from './routes/online-booking'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MembershipBillingRouteImport } from './routes/membership-billing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InstallationsRouteImport } from './routes/installations'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as ExecutiveDashboardRouteImport } from './routes/executive-dashboard'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomerPortalRouteImport } from './routes/customer-portal'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as BusinessIntelligenceRouteImport } from './routes/business-intelligence'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ApiAccessRouteImport } from './routes/api-access'
import { Route as AiBrainRouteImport } from './routes/ai-brain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InventoryWarehouseRouteImport } from './routes/inventory.warehouse'
import { Route as InventoryVansRouteImport } from './routes/inventory.vans'
import { Route as InventoryTransferRouteImport } from './routes/inventory.transfer'
import { Route as InventoryReportsRouteImport } from './routes/inventory.reports'
import { Route as InventoryLowStockRouteImport } from './routes/inventory.low-stock'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as EstimatesNewRouteImport } from './routes/estimates.new'
import { Route as EstimatesEstimateIdRouteImport } from './routes/estimates.$estimateId'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment.$equipmentId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as JobsJobIdPartsRouteImport } from './routes/jobs.$jobId.parts'
import { Route as InventoryItemsNewRouteImport } from './routes/inventory.items.new'
import { Route as EstimatesEstimateIdProposalRouteImport } from './routes/estimates.$estimateId.proposal'
import { Route as InventoryItemsItemIdEditRouteImport } from './routes/inventory.items.$itemId.edit'

const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackingRoute = TimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorsRoute = SubcontractorsRouteImport.update({
  id: '/subcontractors',
  path: '/subcontractors',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCatalogRoute = ServicesCatalogRouteImport.update({
  id: '/services-catalog',
  path: '/services-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCatalogRoute = SalesCatalogRouteImport.update({
  id: '/sales-catalog',
  path: '/sales-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventiveMaintenanceRoute = PreventiveMaintenanceRouteImport.update({
  id: '/preventive-maintenance',
  path: '/preventive-maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineBookingRoute = OnlineBookingRouteImport.update({
  id: '/online-booking',
  path: '/online-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipBillingRoute = MembershipBillingRouteImport.update({
  id: '/membership-billing',
  path: '/membership-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsRoute = InstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveDashboardRoute = ExecutiveDashboardRouteImport.update({
  id: '/executive-dashboard',
  path: '/executive-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPortalRoute = CustomerPortalRouteImport.update({
  id: '/customer-portal',
  path: '/customer-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIntelligenceRoute = BusinessIntelligenceRouteImport.update({
  id: '/business-intelligence',
  path: '/business-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBrainRoute = AiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PropertiesRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InventoryWarehouseRoute = InventoryWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryVansRoute = InventoryVansRouteImport.update({
  id: '/vans',
  path: '/vans',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryTransferRoute = InventoryTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryReportsRoute = InventoryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryLowStockRoute = InventoryLowStockRouteImport.update({
  id: '/low-stock',
  path: '/low-stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => InventoryRoute,
} as any)
const EstimatesNewRoute = EstimatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EstimatesRoute,
} as any)
const EstimatesEstimateIdRoute = EstimatesEstimateIdRouteImport.update({
  id: '/$estimateId',
  path: '/$estimateId',
  getParentRoute: () => EstimatesRoute,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => EquipmentRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)
const JobsJobIdPartsRoute = JobsJobIdPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const InventoryItemsNewRoute = InventoryItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryItemsRoute,
} as any)
const EstimatesEstimateIdProposalRoute =
  EstimatesEstimateIdProposalRouteImport.update({
    id: '/proposal',
    path: '/proposal',
    getParentRoute: () => EstimatesEstimateIdRoute,
  } as any)
const InventoryItemsItemIdEditRoute =
  InventoryItemsItemIdEditRouteImport.update({
    id: '/$itemId/edit',
    path: '/$itemId/edit',
    getParentRoute: () => InventoryItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/api-access': typeof ApiAccessRoute
  '/assets': typeof AssetsRoute
  '/automation': typeof AutomationRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/commercial': typeof CommercialRoute
  '/commissions': typeof CommissionsRoute
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/financing': typeof FinancingRoute
  '/fleet': typeof FleetRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRoute
  '/installations': typeof InstallationsRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/membership-billing': typeof MembershipBillingRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/online-booking': typeof OnlineBookingRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/pipeline': typeof PipelineRoute
  '/preventive-maintenance': typeof PreventiveMaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sales-catalog': typeof SalesCatalogRoute
  '/schedule': typeof ScheduleRoute
  '/services-catalog': typeof ServicesCatalogRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
  '/inventory/items/$itemId/edit': typeof InventoryItemsItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/api-access': typeof ApiAccessRoute
  '/assets': typeof AssetsRoute
  '/automation': typeof AutomationRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/commercial': typeof CommercialRoute
  '/commissions': typeof CommissionsRoute
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/financing': typeof FinancingRoute
  '/fleet': typeof FleetRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRoute
  '/installations': typeof InstallationsRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/membership-billing': typeof MembershipBillingRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/online-booking': typeof OnlineBookingRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/pipeline': typeof PipelineRoute
  '/preventive-maintenance': typeof PreventiveMaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sales-catalog': typeof SalesCatalogRoute
  '/schedule': typeof ScheduleRoute
  '/services-catalog': typeof ServicesCatalogRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/inventory': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
  '/inventory/items/$itemId/edit': typeof InventoryItemsItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/api-access': typeof ApiAccessRoute
  '/assets': typeof AssetsRoute
  '/automation': typeof AutomationRoute
  '/business-intelligence': typeof BusinessIntelligenceRoute
  '/commercial': typeof CommercialRoute
  '/commissions': typeof CommissionsRoute
  '/communications': typeof CommunicationsRoute
  '/crm': typeof CrmRoute
  '/customer-portal': typeof CustomerPortalRoute
  '/customers': typeof CustomersRouteWithChildren
  '/dispatch': typeof DispatchRoute
  '/documents': typeof DocumentsRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/estimates': typeof EstimatesRouteWithChildren
  '/executive-dashboard': typeof ExecutiveDashboardRoute
  '/financing': typeof FinancingRoute
  '/fleet': typeof FleetRoute
  '/forecasting': typeof ForecastingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forms': typeof FormsRoute
  '/installations': typeof InstallationsRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/membership-billing': typeof MembershipBillingRoute
  '/memberships': typeof MembershipsRoute
  '/notifications': typeof NotificationsRoute
  '/online-booking': typeof OnlineBookingRoute
  '/payments': typeof PaymentsRoute
  '/payroll': typeof PayrollRoute
  '/pipeline': typeof PipelineRoute
  '/preventive-maintenance': typeof PreventiveMaintenanceRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sales-catalog': typeof SalesCatalogRoute
  '/schedule': typeof ScheduleRoute
  '/services-catalog': typeof ServicesCatalogRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sla': typeof SlaRoute
  '/subcontractors': typeof SubcontractorsRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/time-tracking': typeof TimeTrackingRoute
  '/training': typeof TrainingRoute
  '/vendors': typeof VendorsRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/low-stock': typeof InventoryLowStockRoute
  '/inventory/reports': typeof InventoryReportsRoute
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/inventory/': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
  '/inventory/items/$itemId/edit': typeof InventoryItemsItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-brain'
    | '/api-access'
    | '/assets'
    | '/automation'
    | '/business-intelligence'
    | '/commercial'
    | '/commissions'
    | '/communications'
    | '/crm'
    | '/customer-portal'
    | '/customers'
    | '/dispatch'
    | '/documents'
    | '/equipment'
    | '/estimates'
    | '/executive-dashboard'
    | '/financing'
    | '/fleet'
    | '/forecasting'
    | '/forgot-password'
    | '/forms'
    | '/installations'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/locations'
    | '/login'
    | '/membership-billing'
    | '/memberships'
    | '/notifications'
    | '/online-booking'
    | '/payments'
    | '/payroll'
    | '/pipeline'
    | '/preventive-maintenance'
    | '/projects'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/reviews'
    | '/sales-catalog'
    | '/schedule'
    | '/services-catalog'
    | '/settings'
    | '/signup'
    | '/sla'
    | '/subcontractors'
    | '/technicians'
    | '/tickets'
    | '/time-tracking'
    | '/training'
    | '/vendors'
    | '/customers/$customerId'
    | '/equipment/$equipmentId'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/low-stock'
    | '/inventory/reports'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/jobs/$jobId'
    | '/properties/$propertyId'
    | '/inventory/'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
    | '/inventory/items/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-brain'
    | '/api-access'
    | '/assets'
    | '/automation'
    | '/business-intelligence'
    | '/commercial'
    | '/commissions'
    | '/communications'
    | '/crm'
    | '/customer-portal'
    | '/customers'
    | '/dispatch'
    | '/documents'
    | '/equipment'
    | '/estimates'
    | '/executive-dashboard'
    | '/financing'
    | '/fleet'
    | '/forecasting'
    | '/forgot-password'
    | '/forms'
    | '/installations'
    | '/integrations'
    | '/invoices'
    | '/jobs'
    | '/locations'
    | '/login'
    | '/membership-billing'
    | '/memberships'
    | '/notifications'
    | '/online-booking'
    | '/payments'
    | '/payroll'
    | '/pipeline'
    | '/preventive-maintenance'
    | '/projects'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/reviews'
    | '/sales-catalog'
    | '/schedule'
    | '/services-catalog'
    | '/settings'
    | '/signup'
    | '/sla'
    | '/subcontractors'
    | '/technicians'
    | '/tickets'
    | '/time-tracking'
    | '/training'
    | '/vendors'
    | '/customers/$customerId'
    | '/equipment/$equipmentId'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/low-stock'
    | '/inventory/reports'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/jobs/$jobId'
    | '/properties/$propertyId'
    | '/inventory'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
    | '/inventory/items/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/ai-brain'
    | '/api-access'
    | '/assets'
    | '/automation'
    | '/business-intelligence'
    | '/commercial'
    | '/commissions'
    | '/communications'
    | '/crm'
    | '/customer-portal'
    | '/customers'
    | '/dispatch'
    | '/documents'
    | '/equipment'
    | '/estimates'
    | '/executive-dashboard'
    | '/financing'
    | '/fleet'
    | '/forecasting'
    | '/forgot-password'
    | '/forms'
    | '/installations'
    | '/integrations'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/locations'
    | '/login'
    | '/membership-billing'
    | '/memberships'
    | '/notifications'
    | '/online-booking'
    | '/payments'
    | '/payroll'
    | '/pipeline'
    | '/preventive-maintenance'
    | '/projects'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/reviews'
    | '/sales-catalog'
    | '/schedule'
    | '/services-catalog'
    | '/settings'
    | '/signup'
    | '/sla'
    | '/subcontractors'
    | '/technicians'
    | '/tickets'
    | '/time-tracking'
    | '/training'
    | '/vendors'
    | '/customers/$customerId'
    | '/equipment/$equipmentId'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/low-stock'
    | '/inventory/reports'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/jobs/$jobId'
    | '/properties/$propertyId'
    | '/inventory/'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
    | '/inventory/items/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBrainRoute: typeof AiBrainRoute
  ApiAccessRoute: typeof ApiAccessRoute
  AssetsRoute: typeof AssetsRoute
  AutomationRoute: typeof AutomationRoute
  BusinessIntelligenceRoute: typeof BusinessIntelligenceRoute
  CommercialRoute: typeof CommercialRoute
  CommissionsRoute: typeof CommissionsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  CrmRoute: typeof CrmRoute
  CustomerPortalRoute: typeof CustomerPortalRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DispatchRoute: typeof DispatchRoute
  DocumentsRoute: typeof DocumentsRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
  EstimatesRoute: typeof EstimatesRouteWithChildren
  ExecutiveDashboardRoute: typeof ExecutiveDashboardRoute
  FinancingRoute: typeof FinancingRoute
  FleetRoute: typeof FleetRoute
  ForecastingRoute: typeof ForecastingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FormsRoute: typeof FormsRoute
  InstallationsRoute: typeof InstallationsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  InvoicesRoute: typeof InvoicesRoute
  JobsRoute: typeof JobsRouteWithChildren
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  MembershipBillingRoute: typeof MembershipBillingRoute
  MembershipsRoute: typeof MembershipsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnlineBookingRoute: typeof OnlineBookingRoute
  PaymentsRoute: typeof PaymentsRoute
  PayrollRoute: typeof PayrollRoute
  PipelineRoute: typeof PipelineRoute
  PreventiveMaintenanceRoute: typeof PreventiveMaintenanceRoute
  ProjectsRoute: typeof ProjectsRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SalesCatalogRoute: typeof SalesCatalogRoute
  ScheduleRoute: typeof ScheduleRoute
  ServicesCatalogRoute: typeof ServicesCatalogRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SlaRoute: typeof SlaRoute
  SubcontractorsRoute: typeof SubcontractorsRoute
  TechniciansRoute: typeof TechniciansRoute
  TicketsRoute: typeof TicketsRoute
  TimeTrackingRoute: typeof TimeTrackingRoute
  TrainingRoute: typeof TrainingRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking': {
      id: '/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractors': {
      id: '/subcontractors'
      path: '/subcontractors'
      fullPath: '/subcontractors'
      preLoaderRoute: typeof SubcontractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-catalog': {
      id: '/services-catalog'
      path: '/services-catalog'
      fullPath: '/services-catalog'
      preLoaderRoute: typeof ServicesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-catalog': {
      id: '/sales-catalog'
      path: '/sales-catalog'
      fullPath: '/sales-catalog'
      preLoaderRoute: typeof SalesCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventive-maintenance': {
      id: '/preventive-maintenance'
      path: '/preventive-maintenance'
      fullPath: '/preventive-maintenance'
      preLoaderRoute: typeof PreventiveMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-booking': {
      id: '/online-booking'
      path: '/online-booking'
      fullPath: '/online-booking'
      preLoaderRoute: typeof OnlineBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-billing': {
      id: '/membership-billing'
      path: '/membership-billing'
      fullPath: '/membership-billing'
      preLoaderRoute: typeof MembershipBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations': {
      id: '/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof InstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-dashboard': {
      id: '/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof ExecutiveDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-portal': {
      id: '/customer-portal'
      path: '/customer-portal'
      fullPath: '/customer-portal'
      preLoaderRoute: typeof CustomerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-intelligence': {
      id: '/business-intelligence'
      path: '/business-intelligence'
      fullPath: '/business-intelligence'
      preLoaderRoute: typeof BusinessIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-access': {
      id: '/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-brain': {
      id: '/ai-brain'
      path: '/ai-brain'
      fullPath: '/ai-brain'
      preLoaderRoute: typeof AiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/inventory/warehouse': {
      id: '/inventory/warehouse'
      path: '/warehouse'
      fullPath: '/inventory/warehouse'
      preLoaderRoute: typeof InventoryWarehouseRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/vans': {
      id: '/inventory/vans'
      path: '/vans'
      fullPath: '/inventory/vans'
      preLoaderRoute: typeof InventoryVansRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/transfer': {
      id: '/inventory/transfer'
      path: '/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof InventoryTransferRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/reports': {
      id: '/inventory/reports'
      path: '/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof InventoryReportsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/low-stock': {
      id: '/inventory/low-stock'
      path: '/low-stock'
      fullPath: '/inventory/low-stock'
      preLoaderRoute: typeof InventoryLowStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/estimates/new': {
      id: '/estimates/new'
      path: '/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof EstimatesNewRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/estimates/$estimateId': {
      id: '/estimates/$estimateId'
      path: '/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof EstimatesEstimateIdRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/equipment/$equipmentId': {
      id: '/equipment/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/jobs/$jobId/parts': {
      id: '/jobs/$jobId/parts'
      path: '/parts'
      fullPath: '/jobs/$jobId/parts'
      preLoaderRoute: typeof JobsJobIdPartsRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/inventory/items/new': {
      id: '/inventory/items/new'
      path: '/new'
      fullPath: '/inventory/items/new'
      preLoaderRoute: typeof InventoryItemsNewRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
    '/estimates/$estimateId/proposal': {
      id: '/estimates/$estimateId/proposal'
      path: '/proposal'
      fullPath: '/estimates/$estimateId/proposal'
      preLoaderRoute: typeof EstimatesEstimateIdProposalRouteImport
      parentRoute: typeof EstimatesEstimateIdRoute
    }
    '/inventory/items/$itemId/edit': {
      id: '/inventory/items/$itemId/edit'
      path: '/$itemId/edit'
      fullPath: '/inventory/items/$itemId/edit'
      preLoaderRoute: typeof InventoryItemsItemIdEditRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface EquipmentRouteChildren {
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

interface EstimatesEstimateIdRouteChildren {
  EstimatesEstimateIdProposalRoute: typeof EstimatesEstimateIdProposalRoute
}

const EstimatesEstimateIdRouteChildren: EstimatesEstimateIdRouteChildren = {
  EstimatesEstimateIdProposalRoute: EstimatesEstimateIdProposalRoute,
}

const EstimatesEstimateIdRouteWithChildren =
  EstimatesEstimateIdRoute._addFileChildren(EstimatesEstimateIdRouteChildren)

interface EstimatesRouteChildren {
  EstimatesEstimateIdRoute: typeof EstimatesEstimateIdRouteWithChildren
  EstimatesNewRoute: typeof EstimatesNewRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesEstimateIdRoute: EstimatesEstimateIdRouteWithChildren,
  EstimatesNewRoute: EstimatesNewRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface InventoryItemsRouteChildren {
  InventoryItemsNewRoute: typeof InventoryItemsNewRoute
  InventoryItemsItemIdEditRoute: typeof InventoryItemsItemIdEditRoute
}

const InventoryItemsRouteChildren: InventoryItemsRouteChildren = {
  InventoryItemsNewRoute: InventoryItemsNewRoute,
  InventoryItemsItemIdEditRoute: InventoryItemsItemIdEditRoute,
}

const InventoryItemsRouteWithChildren = InventoryItemsRoute._addFileChildren(
  InventoryItemsRouteChildren,
)

interface InventoryRouteChildren {
  InventoryItemsRoute: typeof InventoryItemsRouteWithChildren
  InventoryLowStockRoute: typeof InventoryLowStockRoute
  InventoryReportsRoute: typeof InventoryReportsRoute
  InventoryTransferRoute: typeof InventoryTransferRoute
  InventoryVansRoute: typeof InventoryVansRoute
  InventoryWarehouseRoute: typeof InventoryWarehouseRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemsRoute: InventoryItemsRouteWithChildren,
  InventoryLowStockRoute: InventoryLowStockRoute,
  InventoryReportsRoute: InventoryReportsRoute,
  InventoryTransferRoute: InventoryTransferRoute,
  InventoryVansRoute: InventoryVansRoute,
  InventoryWarehouseRoute: InventoryWarehouseRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface JobsJobIdRouteChildren {
  JobsJobIdPartsRoute: typeof JobsJobIdPartsRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdPartsRoute: JobsJobIdPartsRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface PropertiesRouteChildren {
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBrainRoute: AiBrainRoute,
  ApiAccessRoute: ApiAccessRoute,
  AssetsRoute: AssetsRoute,
  AutomationRoute: AutomationRoute,
  BusinessIntelligenceRoute: BusinessIntelligenceRoute,
  CommercialRoute: CommercialRoute,
  CommissionsRoute: CommissionsRoute,
  CommunicationsRoute: CommunicationsRoute,
  CrmRoute: CrmRoute,
  CustomerPortalRoute: CustomerPortalRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DispatchRoute: DispatchRoute,
  DocumentsRoute: DocumentsRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
  EstimatesRoute: EstimatesRouteWithChildren,
  ExecutiveDashboardRoute: ExecutiveDashboardRoute,
  FinancingRoute: FinancingRoute,
  FleetRoute: FleetRoute,
  ForecastingRoute: ForecastingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FormsRoute: FormsRoute,
  InstallationsRoute: InstallationsRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryRoute: InventoryRouteWithChildren,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRouteWithChildren,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  MembershipBillingRoute: MembershipBillingRoute,
  MembershipsRoute: MembershipsRoute,
  NotificationsRoute: NotificationsRoute,
  OnlineBookingRoute: OnlineBookingRoute,
  PaymentsRoute: PaymentsRoute,
  PayrollRoute: PayrollRoute,
  PipelineRoute: PipelineRoute,
  PreventiveMaintenanceRoute: PreventiveMaintenanceRoute,
  ProjectsRoute: ProjectsRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SalesCatalogRoute: SalesCatalogRoute,
  ScheduleRoute: ScheduleRoute,
  ServicesCatalogRoute: ServicesCatalogRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SlaRoute: SlaRoute,
  SubcontractorsRoute: SubcontractorsRoute,
  TechniciansRoute: TechniciansRoute,
  TicketsRoute: TicketsRoute,
  TimeTrackingRoute: TimeTrackingRoute,
  TrainingRoute: TrainingRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
