/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EstimatesRouteImport } from './routes/estimates'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as InventoryWarehouseRouteImport } from './routes/inventory.warehouse'
import { Route as InventoryVansRouteImport } from './routes/inventory.vans'
import { Route as InventoryTransferRouteImport } from './routes/inventory.transfer'
import { Route as InventoryItemsRouteImport } from './routes/inventory.items'
import { Route as EstimatesNewRouteImport } from './routes/estimates.new'
import { Route as EstimatesEstimateIdRouteImport } from './routes/estimates.$estimateId'
import { Route as JobsJobIdPartsRouteImport } from './routes/jobs.$jobId.parts'
import { Route as InventoryItemsNewRouteImport } from './routes/inventory.items.new'
import { Route as EstimatesEstimateIdProposalRouteImport } from './routes/estimates.$estimateId.proposal'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesRoute = EstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryWarehouseRoute = InventoryWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryVansRoute = InventoryVansRouteImport.update({
  id: '/vans',
  path: '/vans',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryTransferRoute = InventoryTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryItemsRoute = InventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => InventoryRoute,
} as any)
const EstimatesNewRoute = EstimatesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EstimatesRoute,
} as any)
const EstimatesEstimateIdRoute = EstimatesEstimateIdRouteImport.update({
  id: '/$estimateId',
  path: '/$estimateId',
  getParentRoute: () => EstimatesRoute,
} as any)
const JobsJobIdPartsRoute = JobsJobIdPartsRouteImport.update({
  id: '/$jobId/parts',
  path: '/$jobId/parts',
  getParentRoute: () => JobsRoute,
} as any)
const InventoryItemsNewRoute = InventoryItemsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InventoryItemsRoute,
} as any)
const EstimatesEstimateIdProposalRoute =
  EstimatesEstimateIdProposalRouteImport.update({
    id: '/proposal',
    path: '/proposal',
    getParentRoute: () => EstimatesEstimateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/equipment': typeof EquipmentRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/inventory/': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/equipment': typeof EquipmentRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/inventory': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/equipment': typeof EquipmentRoute
  '/estimates': typeof EstimatesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/invoices': typeof InvoicesRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/technicians': typeof TechniciansRoute
  '/tickets': typeof TicketsRoute
  '/estimates/$estimateId': typeof EstimatesEstimateIdRouteWithChildren
  '/estimates/new': typeof EstimatesNewRoute
  '/inventory/items': typeof InventoryItemsRouteWithChildren
  '/inventory/transfer': typeof InventoryTransferRoute
  '/inventory/vans': typeof InventoryVansRoute
  '/inventory/warehouse': typeof InventoryWarehouseRoute
  '/inventory/': typeof InventoryIndexRoute
  '/estimates/$estimateId/proposal': typeof EstimatesEstimateIdProposalRoute
  '/inventory/items/new': typeof InventoryItemsNewRoute
  '/jobs/$jobId/parts': typeof JobsJobIdPartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dispatch'
    | '/equipment'
    | '/estimates'
    | '/forgot-password'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/pipeline'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/technicians'
    | '/tickets'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/inventory/'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dispatch'
    | '/equipment'
    | '/estimates'
    | '/forgot-password'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/pipeline'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/technicians'
    | '/tickets'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/inventory'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dispatch'
    | '/equipment'
    | '/estimates'
    | '/forgot-password'
    | '/inventory'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/pipeline'
    | '/properties'
    | '/purchase-orders'
    | '/reports'
    | '/reset-password'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/technicians'
    | '/tickets'
    | '/estimates/$estimateId'
    | '/estimates/new'
    | '/inventory/items'
    | '/inventory/transfer'
    | '/inventory/vans'
    | '/inventory/warehouse'
    | '/inventory/'
    | '/estimates/$estimateId/proposal'
    | '/inventory/items/new'
    | '/jobs/$jobId/parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DispatchRoute: typeof DispatchRoute
  EquipmentRoute: typeof EquipmentRoute
  EstimatesRoute: typeof EstimatesRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  InvoicesRoute: typeof InvoicesRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  PropertiesRoute: typeof PropertiesRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TechniciansRoute: typeof TechniciansRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates': {
      id: '/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof EstimatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/warehouse': {
      id: '/inventory/warehouse'
      path: '/warehouse'
      fullPath: '/inventory/warehouse'
      preLoaderRoute: typeof InventoryWarehouseRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/vans': {
      id: '/inventory/vans'
      path: '/vans'
      fullPath: '/inventory/vans'
      preLoaderRoute: typeof InventoryVansRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/transfer': {
      id: '/inventory/transfer'
      path: '/transfer'
      fullPath: '/inventory/transfer'
      preLoaderRoute: typeof InventoryTransferRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/items': {
      id: '/inventory/items'
      path: '/items'
      fullPath: '/inventory/items'
      preLoaderRoute: typeof InventoryItemsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/estimates/new': {
      id: '/estimates/new'
      path: '/new'
      fullPath: '/estimates/new'
      preLoaderRoute: typeof EstimatesNewRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/estimates/$estimateId': {
      id: '/estimates/$estimateId'
      path: '/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof EstimatesEstimateIdRouteImport
      parentRoute: typeof EstimatesRoute
    }
    '/jobs/$jobId/parts': {
      id: '/jobs/$jobId/parts'
      path: '/$jobId/parts'
      fullPath: '/jobs/$jobId/parts'
      preLoaderRoute: typeof JobsJobIdPartsRouteImport
      parentRoute: typeof JobsRoute
    }
    '/inventory/items/new': {
      id: '/inventory/items/new'
      path: '/new'
      fullPath: '/inventory/items/new'
      preLoaderRoute: typeof InventoryItemsNewRouteImport
      parentRoute: typeof InventoryItemsRoute
    }
    '/estimates/$estimateId/proposal': {
      id: '/estimates/$estimateId/proposal'
      path: '/proposal'
      fullPath: '/estimates/$estimateId/proposal'
      preLoaderRoute: typeof EstimatesEstimateIdProposalRouteImport
      parentRoute: typeof EstimatesEstimateIdRoute
    }
  }
}

interface EstimatesEstimateIdRouteChildren {
  EstimatesEstimateIdProposalRoute: typeof EstimatesEstimateIdProposalRoute
}

const EstimatesEstimateIdRouteChildren: EstimatesEstimateIdRouteChildren = {
  EstimatesEstimateIdProposalRoute: EstimatesEstimateIdProposalRoute,
}

const EstimatesEstimateIdRouteWithChildren =
  EstimatesEstimateIdRoute._addFileChildren(EstimatesEstimateIdRouteChildren)

interface EstimatesRouteChildren {
  EstimatesEstimateIdRoute: typeof EstimatesEstimateIdRouteWithChildren
  EstimatesNewRoute: typeof EstimatesNewRoute
}

const EstimatesRouteChildren: EstimatesRouteChildren = {
  EstimatesEstimateIdRoute: EstimatesEstimateIdRouteWithChildren,
  EstimatesNewRoute: EstimatesNewRoute,
}

const EstimatesRouteWithChildren = EstimatesRoute._addFileChildren(
  EstimatesRouteChildren,
)

interface InventoryItemsRouteChildren {
  InventoryItemsNewRoute: typeof InventoryItemsNewRoute
}

const InventoryItemsRouteChildren: InventoryItemsRouteChildren = {
  InventoryItemsNewRoute: InventoryItemsNewRoute,
}

const InventoryItemsRouteWithChildren = InventoryItemsRoute._addFileChildren(
  InventoryItemsRouteChildren,
)

interface InventoryRouteChildren {
  InventoryItemsRoute: typeof InventoryItemsRouteWithChildren
  InventoryTransferRoute: typeof InventoryTransferRoute
  InventoryVansRoute: typeof InventoryVansRoute
  InventoryWarehouseRoute: typeof InventoryWarehouseRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemsRoute: InventoryItemsRouteWithChildren,
  InventoryTransferRoute: InventoryTransferRoute,
  InventoryVansRoute: InventoryVansRoute,
  InventoryWarehouseRoute: InventoryWarehouseRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdPartsRoute: typeof JobsJobIdPartsRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdPartsRoute: JobsJobIdPartsRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DispatchRoute: DispatchRoute,
  EquipmentRoute: EquipmentRoute,
  EstimatesRoute: EstimatesRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventoryRoute: InventoryRouteWithChildren,
  InvoicesRoute: InvoicesRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  PropertiesRoute: PropertiesRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TechniciansRoute: TechniciansRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
